const express = require("express");
const cors = require("cors");
const db = require("./config/db.config");
const dotenv = require("dotenv");
const fs = require('fs');
const https = require('https');
const http = require('http'); // To handle HTTP and redirect to HTTPS

const studentRoute = require('./routes/studentRoute');
const departmentInchargeRoute = require('./routes/departmentInchargeRoute');
const eventCoordinatorRoute = require('./controllers/eventCoordinatorController');

dotenv.config();

// Creating the express app
const app = express();
const port = process.env.SERVER_PORT || 5555; // HTTPS port should be 443

// Setting up middlewares
const corsOptions = {
  origin: 'https://sathyabama-techno-summit-2024.vercel.app', // Replace with your Vercel frontend URL (remove trailing slash)
  optionsSuccessStatus: 200,
};

app.use(cors(corsOptions));
app.use(express.json());

// Setting up the routes
app.use('/student', studentRoute);
app.use('/departmentIncharge', departmentInchargeRoute);
app.post('/eventCoordinator/login', eventCoordinatorRoute.coordinatorLogin);
app.post('/eventCoordinator/download',eventCoordinatorRoute.download,eventCoordinatorRoute.linkdownload)

// HTTPS certificates path (generated by Certbot)
const sslOptions = {
  key: fs.readFileSync('/etc/letsencrypt/live/sathyabama-technosummit-2024.in/privkey.pem'),
  cert: fs.readFileSync('/etc/letsencrypt/live/sathyabama-technosummit-2024.in/fullchain.pem'),
};

// HTTPS server
https.createServer(sslOptions, app).listen(443, () => {
  console.log('HTTPS Server started at port 443');
});

// HTTP to HTTPS redirection (Optional but recommended)
http.createServer((req, res) => {
  res.writeHead(301, { "Location": "https://" + req.headers['host'] + req.url });
  res.end();
}).listen(80, () => {
  console.log('HTTP Server started on port 80, redirecting to HTTPS');
});


